### ISSUE TITLE
请教一个问题，关于atomic在link中的使用

### ISSUE THREAD

**Issue by wbpmrck** [funny/link#24]
读您的代码，在很多地方看到了CAS的使用，但是我理解，在很多地方应该不会有多个线程同时访问的，比如server.go的line 89(为new session分配id),以及stop server的地方。
能否简单解释一下呢，什么情况下会多线程访问？

**Comment by wbpmrck** [comment]
另外补充一个疑问，在examples/echo_server/main.go 的line 40,有这么一句：return session.Send(link.Bytes(msg.Data))，为什么Send方法需要传入一个encoder?对于应用开发者来说，更简单的方式难道不是send一个[]byte吗。
另外link.Bytes通过一个 []byte生成一个函数并返回，这个函数对象每次业务调用Send都会生成一个，这样会不会造成额外的开销？

**Comment by cfc4n** [comment]
1，之前没在意，@wbpmrck 这么一说，认真看了下代码，link包中只有一处对maxSessionId做更改的地方 Accept方法内。而Accept方法只有一处调用，就是Serve方法。这里接受客户端请求，再for里一个一个的被AcceptServe方法处理，增加maxSessionId的数值，没有多线（协）程，可以不用原子操作吧？

2，这么做，多数是为了方便开发者自定义通讯协议，抽象化一下，方便更改通讯的数据包格式。　这种开销，可以忽略不计。其他地方少个io，或者少个循环，远比这点开销节省大多了。

期待达达的解答。

**Comment by idada** [comment]
@wbpmrck @cfc4n 

server.go 里面使用atomic操作分配Session ID是一个历史遗留问题，之前的接口设计上存在两种风格的API，分别是现在的循环Accept和手工单次的Accept，手工单次Accept是可以被调用者放到多个goroutine执行的，所以才会需要atomic操作来分配Session ID，当前版本是可以去掉了。

对于session.Send的参数设计，是有意这么做的。如果由调用者传递一个[]byte进到link包，link包的分包协议再发送这个[]byte时只有两种选择：

1. 将外部传递进来的[]byte填充到消息分包中。
2. 先发消息分包头再发外部传递进来的[]byte数据。

这两个做法一个是增加数据拷贝，一个是增加IO次数。

所以link包引入一个OutBuffer的设计，OutBuffer包含了消息包的包头结构，由调用者填充包体，就可以减少数据拷贝，发送也只需要单次发送。

其次，外部传递 []byte进来，也就意味着[]byte是外部创建的，而OutBuffer的设计是由link包来管理对象，可以做到内部维护对象池，做对象复用，也可以进一步提高效率。

**Comment by wbpmrck** [comment]
@idada 
关于最后的OutBuffer的设计，我明白是为了在发送时进行buffer回收，但是我的意思是，“要发送的数据是用户决定，并在外部创建的”这一事实，是无法改变的。比如我需要发送一个怪物信息给用户，这个数据，无论如何框架是无法实现知道的，所以这部分数据的buffer一定是外部创建的。
比如你的例子里的link.Bytes(msg.Data)，这里的msg.Data一定是外部创建的（只不过你的例子里刚好用了接收的[]byte）。
假设Send方法接收一个[]byte,不是一样可以append到OutBuffer里去吗，本质上是一样的。
相反现在这个API使用起来不是很直观，理解起来很别扭，它其实还是使用了一个函数闭包，比如这个内置函数：
func Bytes(v []byte) Encoder {
	return func(buffer *OutBuffer) error {
		buffer.WriteBytes(v) //这里仍然引用了闭包外部的一个参数变量v,来保存真正的数据
		return nil
	}
}
不知道我是否表达清楚了。

**Comment by wbpmrck** [comment]
@idada 
顺便再补充一个疑问，是关于InBuffer的频繁获取和回收的。烦请你解惑，感谢~
先提出我的看法是：对于一个网络服务端，由于不知道什么时候会有数据过来，所以每个session必然是要预留一个InBuffer的，而不需要回收。

比如，在session.go里，对于InBuffer的获取，是在ProcessOnce方法里，通过buffer := newInBuffer()来得到的，然后当decoder使用完成之后，再通过buffer.free()来回收。
但是，ProcessOnce方法在外部，是不断循环执行的，也就意味着InBuffer在这个过程中不断的从pool中取出、交回。（而且实际上每时每刻，每个session都会有一个从pool获取的InBuffer，这和Session直接持有没有太大区别）
我想是不是对于Session来说，它直接持有一个InBuffer来的更有效率，不需要反复get和free了？

**Comment by idada** [comment]
@wbpmrck 

非常感谢你提到建议，你提的建议都很好。

我们先说下`OutBuffer`的设计问题，我们设想一个游戏请求处理过程：

```go
func API_GetPlayerItemById(itemId int64) {
    item := gamedb.PlayerItems.Lookup(itemId)

    gamenet.Send(gamenet.API.GetItemResult {
       item
    })
}
```

游戏中用于表达数据的是实体对象，所以需要从游戏中发送一个对象到客户端时，必然需要一个编码过程，比如上面的伪代码中，`gamenet.Send()`需要把`gamenet.API.GetItemResult`转成`[]byte`再进行发送，不管这个程序用的是原生net包还是link包，这一步是省不了的。

减少数据复制的差异点是在于编码的过程，如果是直接编码成`[]byte`再发送，这时候网络发送接口只拿到了包体，包头没拿到，要构造一个完整消息包，就需要创建一个够大的`[]byte`把包头和包体写入进去，再发送，这样就要发生两次make([]byte)和数据拷贝。

如果在编码过程中是把数据写入`OutBuffer`，因为`OutBuffer`是由link包的分包协议`Prepare`过的，所以已经预备好了足够大的空间，将数据顺序写入`OutBuffer`后就可以一次发送了，这样就减少了一次数据复制。

如果程序非得自己把实体对象序列化到`[]byte`，再`Append`到`OutBuffer`，那只能说是用法错误。但是至少也还是比没有`OutBuffer`的时候，少了一次`make`，因为`OutBuffer`是重用的。

对于你说的接口清晰度问题，之前的版本是有个一个Message接口类型：

```go
type Message interface {
    RecommendPacketSize() int
    WritePacket(*OutBuffer) error
}
```

这个接口可以让分包协议在`Prepare`消息包的时候一次创建足够大的内存空间，但是每个程序消息都要实现成`Message`接口，我觉比较繁琐，所以就改成了现在的形式。

我想的确是应该保留这个接口，同时内部用回调的方式实现这个接口，这样可以两全其美。

大概会像这样：

```go
type Message interface {
    BufferSize() int
    WriteBuffer(*OutBuffer) error
}

type encoder func(*OutBuffer) error

func (e encoder) BufferSize() int {
    return 1024
}

func (e encoder) WriteBuffer(buffer *OutBuffer) error {
    return e(buffer)
}

func (session *Session) Send(message Message) error {
   ........
}

func (session *Session) SendFunc(callback func(*OutBuffer) error) error {
    return session.Send(encoder(callback))
}
```

调用者可以这样用：

```go

session.Send(MyMessage{data})

session.SendFunc(func(buffer *OutBuffer){
   ......
})
```

对于`InBuffer`和`OutBuffer`频繁获取的问题，我觉得你的建议很好，是应该各个`Session`保持使用，一套`In/OutBuffer`，直到session退出再回收。

没加对象池之前的版本就是像你说的各个`Session`自己有一个重用的`InBuffer`和一个`OutBuffer`，并且接口运行上也允许调用者自己重用Buffer。

前几个版本在做接口简化的时候就把它们去掉了，我会按你提的建议重新加上。

**Comment by wbpmrck** [comment]
@idada 感谢您的解答。^_^
一直十分关注你的项目和博客，希望以后有机会和你多多交流学习。

**Comment by idada** [comment]
@wbpmrck 修改已经提交了，非常感谢大家热心的参与这个项目，提供了很多很有帮助的建议。
