### ISSUE TITLE
atomic.AddUint64(&id, 1) 问题

### ISSUE THREAD

**Issue by liujarrett** [funny/link#25]
我发现atomic.AddUint64(&id, 1) 有问题，link运行2-3天就会崩溃。

**Comment by liujarrett** [comment]
我的环境：
golang 1.3
阿里云 CentOS 6 x64

**Comment by oikomi** [comment]
起码贴出错误堆栈信息啊

**Comment by idada** [comment]
@liujarrett 能不能提供一下错误信息

**Comment by liujarrett** [comment]
时间比较长了，错误信息没有了，报的都是空指针，各种空指针，地方不固定。
当时，我也不知道什么问题，只是怀疑atomic.AddUint64(&id, 1) 有问题。
本来想改link的，但是link多处使用atomic.AddUint64(&id, 1)，就自己写了一个socket server把link替换了，现在运行还算稳定。所以我怀疑atomic.AddUint64(&id, 1)有问题，也不确定。如果大家都没这个问题，可能是我自己的问题。
