### ISSUE TITLE
backend_link.go

### ISSUE THREAD

**Issue by yicaoyimuys** [funny/link#38]
backend_link.go中的dispathMsg函数中
select default中是使用的go conn.close(true)  

如果conn.recvChan被写满了堵塞了的话 后续还有消息到来 会抛出异常send on closed channel

**Comment by yicaoyimuys** [comment]
if conn, exists := this.conns[id]; exists {
		if conn.closeFlag == 0 {
			select {
			case conn.recvChan <- data:
			default:
				go conn.Close()
			}
		}
	}

这样可以吗

**Comment by idada** [comment]
你好，你说的backend_link.go在哪里？

**Comment by yicaoyimuys** [comment]
https://github.com/funny/link/blob/1.1/gateway/backend_link.go
1.1分支里面的

**Comment by idada** [comment]
那份代码旧了，不维护了
