### ISSUE TITLE
消息接收、发送错位

### ISSUE THREAD

**Issue by yicaoyimuys** [funny/link#39]
现在github上的最新的link库   由于session中的Send、Receive去掉了lock
在codec_packet中的encodeHead和decodeHead未做lock处理   会引发消息接收、发送错位
而codec_safe只是对body进行了lock

**Comment by idada** [comment]
你好，能不能提供一下更详细的信息，比如你是怎样进行消息收发，是有多个goroutine同时会调用Session.Send和Session.Receive吗？

**Comment by yicaoyimuys** [comment]
现在出问题的应用场景是，在网关服务器做消息中转到游戏服务器，消息中转时，每个用户客户端Session都是一个goroutine，由这个goroutine直接发送到游戏服务器，也就是多个goroutine同时调用Session.Send

**Comment by yicaoyimuys** [comment]
。。。。。 不好意思 可能是我使用有问题

没有问题的用法：link.ThreadSafe(link.Packet(4, 1024 * 1024, 4096, link.LittleEndian, codetype.NetCodecType{}))

有问题的用法：link.Packet(4, 1024 * 1024, 4096, link.LittleEndian, link.ThreadSafe(codetype.NetCodecType{})

**Comment by idada** [comment]
嗯，是的，应该把ThreadSafe包再最外层
