### ISSUE TITLE
请问下处理性能如何？

### ISSUE THREAD

**Issue by ericx10ng** [funny/link#42]
简单的写了个server, 用link.Packet包上自己的一个CodecType, 解包有时候需要2ms, 有时候会快些400微秒

我写的codectype解包只有这样的的语句(大根10个这样的字段)：
头部
	binary.Read(reader, binary.BigEndian, ...)

body部分：
       ReadFull

是不是我的姿势不对？

**Comment by idada** [comment]
耗时计算是怎么样的逻辑呢？是不是把io等待也计算在内？

**Comment by ericx10ng** [comment]
包是一次收完了的，我是直接用udp

**Comment by idada** [comment]
udp为什么还需要做分包？不是直接读udp包就可以吗？

**Comment by ericx10ng** [comment]
没有分包，是把读到的[]byte, 然后newReader传给packet codectype了
