### ISSUE TITLE
示例中的Manager同时只支持32个session吗

### ISSUE THREAD

**Issue by zrj12345** [funny/link#50]
`func (manager *Manager) putSession(session *Session) {
	smap := &manager.sessionMaps[session.id%sessionMapNum]
	smap.Lock()
	defer smap.Unlock()

	smap.sessions[session.id] = session
	manager.disposeWait.Add(1)
}`

`const sessionMapNum = 32

type Manager struct {
	sessionMaps [sessionMapNum]sessionMap
	disposeFlag bool
	disposeOnce sync.Once
	disposeWait sync.WaitGroup
}`

按照README说的  session的字面含义是会话，就是一次对话过程。每一个连接的生命周期被表达为一个会话过程，这个过程中通讯双方的消息有来有往。
意思是说同时只能有32个连接在线?

**Comment by idada** [comment]
32个sessionMap是为了降低存取session时的锁颗粒度，每个sessionMap里可以存放任意多的Session
