### ISSUE TITLE
能否加上对haproxy proxy协议的支持？

### ISSUE THREAD

**Issue by ericx10ng** [funny/link#52]
需要获取源地址，现在的接口不方便加

**Comment by idada** [comment]
在Protocol构造Codec的时候通过Context返回相关的连接初始化数据，在Handler里拿Context对Session进行初始化，大概是这样一个流程。

**Comment by idada** [comment]
haproxy的协议我没了解过，如果上述过程没办法做到，我们可以进一步讨论

**Comment by idada** [comment]
我这阵子在开发一个网关程序，需要在构造Codec之前进行握手，并拿到握手过程产生的信息来初始化Session，所以加了Context这个东西。

**Comment by ericx10ng** [comment]
嗯，可以做得到
