### ISSUE TITLE
session.go 中的 closeChan 字段有什么用?

### ISSUE THREAD

**Issue by hmli** [funny/link#54]
在整个项目中全局搜索, 发现这个字段只在 `session.go` 的 `Close()` 函数中出现过, 而且是判断 `!= nil` 后就关闭了. 请问这个字段具体是用来做什么的呢?

**Comment by idada** [comment]
在`Close()`中通过`close(session.closeChan)`这句，让`sendLoop()`可以立即退出，`sendLoop()`中通过`select`语法来同时响应两个`chan`的事件。

**Comment by hmli** [comment]
thx

**Comment by hmli** [comment]
我在本地看的源码是某一个旧版本, 可能当时只预留了这个字段, 还没来得及实现具体功能.  我更新到最新版本后就很清晰了.
