### ISSUE TITLE
请教点问题

### ISSUE THREAD

**Issue by qweawdqq** [funny/link#55]
我非常的喜欢golang，所以想仔细认真的学习这门语言。
                        我准备做一个简易的规则引擎服务器小平台，就是向服务传相应的参数  可以返回数字或者是xml
                        一方面加深我的学习，一方面以后的工作中很可能使用到这个平台，
                        但是有些问题我没想明白，所以希望大神能够忙里抽闲，指点我一下，或者给我一个思路。
                        我打算做一个socket 服务器，这样这边的java 用socket连接 发送数据过来就直接可以得到 规则生成的数值了
                        连接这部分应该不算难，也没有涉及到页面，只是数据传输，所以我觉得就不必使用HTTP了
                        但涉及到浏览器页面对数据进行的管理的时候，我就有点想不明白了，这块应该如何 想 http协议  那样进行请求 管理数据啊？
                        大神有没有做过 这样的服务啊？能不能帮忙 给点建议？使用socket是不是合理啊？

**Comment by idada** [comment]
如果做Web接口用http比较合适

**Comment by bg5sbk** [comment]
太久了，关了
