### ISSUE TITLE
请教解码

### ISSUE THREAD

**Issue by suiyunonghen** [funny/link#56]
我看了一下代码，你这个编码器的解码编码是直接挂接到Connection上的，这个时候session的Recive函数做解码处理的时候
msg, err := session.codec.Receive()
	if err != nil {
		session.Close()
	}
这个直接从Connection中获取数据解码，你这个不处理粘包问题？始终能够保证，你这个Con读取出来的都是完整的Json包么？这个无法保证吧，而我去看了Json的，解码代码，他是读取，然后解码失败，就返回了，所以感觉，你这个地方直接绑定，对于粘包的处理，好像没做考虑？

**Comment by idada** [comment]
JSON自动会分，你可以单独做下测试

**Comment by bg5sbk** [comment]
太久了，关了
