### ISSUE TITLE
tcp连接写，是否有必要加锁

### ISSUE THREAD

**Issue by ziyoumeng** [funny/link#60]
你好，在阅读你源码的时候发现个问题想请教下，源码中session的send()方法同步情况下调用session.codec.Send(msg)加了个写锁的目的是什么？如果是为了保证写入数据包的完整性，是没有必要的，tcp底层已经有这个锁了，参见net/fd_unix.go的netFd.Write().

**Comment by cuixin** [comment]
review下了代码，并没有发现在数据write加锁啊，发送时加的锁是针对channel的，为防止close引发和写同时发生，还有就是close保证一次的问题。
