### ISSUE TITLE
关于session的close

### ISSUE THREAD

**Issue by dearjoey** [funny/link#65]
session close的实现是直接关闭了closeChan， 但是如果此时sendChan中还有没法送完的消息，直接close的话，会导致这些消息不会发送成功，所以这个close代表着强制关闭，如果我想要有序的关闭，应该怎么做呢？

**Comment by bg5sbk** [comment]
如果codec实现了ClearSendChan接口，就可以接管最后的消息清理，你可以看下session关闭时的流程
