### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by max-min** [funny/link#67]
1.manager为啥要加一个32的list的session啊？
2.manager和session的各种加锁操作，为啥不通过协程来规避掉， 是因为锁的效率大于协程的处理吗？

**Comment by qinlai** [comment]
1.manager管理session拆分到不同切片可以提高并发性能，写操作只锁影响的切片元素，不需锁整个manager。
2.数据互斥操作一般通过锁控制，锁的效率高于协程，编码也更简洁。

**Comment by max-min** [comment]
thank you！
